spring.application.name=crud_app
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://c3cj4hehegopde.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/d55rp2ec94srqc
spring.datasource.username=ufr5qc3qidqhkl
spring.datasource.password=pae50a370aaabe73edb722c9543f81fc25b5c2716bb3cb8e6946f7a983cfc512e
spring.jpa.show-sql=true



spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
